name: Compilation and static checks CNR

on:
  push:
    paths:
      - cnr/**
      - benches/**
      - .github/**

jobs:
  build:
    name: Build and check
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libhwloc-dev gnuplot libfuse-dev liburcu-dev liburcu6
    - uses: actions/checkout@v3.0.1
    - name: Install rust toolchain
      run: rustup show
    - name: Check formatting
      run: cargo fmt -- --check
      working-directory: ./cnr
    - name: Check formatting (benches)
      run: cargo fmt -- --check
      working-directory: ./benches
    - name: Build CNR
      run: cargo build --release
      working-directory: ./cnr
    - name: Build CNR (unstable)
      run: cargo build --release --features unstable
      working-directory: ./cnr
    - name: Compile tests
      run: cargo test --release --no-run
      working-directory: ./cnr
    - name: Compile benchmarks
      run: |
        cargo bench --bench chashbench --features="c_nr" --no-run
        cargo bench --bench nrfs --features="c_nr" --no-run
        cargo bench --bench lockfree --features="c_nr cmp" --no-run
      working-directory: ./benches
    - name: Execute unit-tests
      run: cargo test
      working-directory: ./cnr
    - name: Try the stack example
      run: RUST_BACKTRACE=1 RUST_LOG='trace' cargo run --release --example stack -- -t1,2 --nop 100000 -l 1 -m sequential
      working-directory: ./cnr
